framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      # async: '%env(MESSENGER_TRANSPORT_DSN)%'
      # failed: 'doctrine://default?queue_name=failed'
      sync: 'sync://'
      async: '%env(MESSENGER_TRANSPORT_DSN)%'

    routing:
      #Relation DomainEvent
      App\Relation\Domain\Event\RelationDeletedEvent: async
      App\Relation\Domain\Event\RelationRenumberedPostsEvent: async

      #FirebaseAuth DomainEvent
      App\FirebaseAuth\Domain\Event\UserRegisteredEvent: async

      #FirebaseAuth
      App\FirebaseAuth\Application\Command\RegisterUser\RegisterUserCommand: async

#      App\Relation\Application\Command\RelationCreate\RelationCreateCommand: sync
#      App\Relation\Application\Command\RelationCreate\RelationCreateCommand: async
#      App\Relation\Application\Command\RelationDelete\RelationDeleteCommand: sync
#      App\Relation\Application\Command\RelationDelete\RelationDeleteCommand: async

when@test:
  framework:
    messenger:
      transports:
        sync: 'sync://'
      routing:
#        App\Relation\Application\Command\RelationCreate\RelationCreateCommand: sync
#        App\Relation\Application\Command\RelationDelete\RelationDeleteCommand: sync
#      transports:
#        # replace with your transport name here (e.g., my_transport: 'in-memory://')
#        # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#        async: 'in-memory://'
